# Generated by Django 3.2.6 on 2022-09-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_auto_20220908_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='picture',
            field=models.URLField(default='http://'),
            preserve_default=False,
        ),
    ]
