# Generated by Django 4.1.1 on 2022-09-10 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_order_orderproducts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='Products.categories'),
        ),
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default='abc', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='categories',
            unique_together={('slug', 'parent')},
        ),
    ]
